In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("log_fw_3.csv", sep=";", header=0)

In [6]:
df

,datetime,ipsrc,ipdst,proto,portsrc,portdst,policyid,action,numproto
0,12/02/2023 03:59,66.249.69.180,17.17.17.17,TCP,57630.0,443.0,1.0,PERMIT,6.0
1,12/02/2023 03:59,66.249.69.178,17.17.17.17,TCP,63808.0,443.0,1.0,PERMIT,6.0
2,12/02/2023 03:59,221.11.125.141,17.17.17.17,TCP,43123.0,2376.0,999.0,DENY,6.0
3,12/02/2023 03:59,183.136.225.42,17.17.17.17,TCP,8088.0,70.0,999.0,DENY,6.0
4,12/02/2023 03:59,38.32.112.34,17.17.17.17,TCP,6356.0,443.0,1.0,PERMIT,6.0
...,...,...,...,...,...,...,...,...,...
999995,01/03/2023 10:54,103.162.10.234,17.17.17.17,TCP,47468.0,443.0,1.0,PERMIT,6.0
999996,01/03/2023 10:54,1.164.127.35,17.17.17.17,TCP,35871.0,23.0,7.0,DENY,6.0
999997,01/03/2023 10:54,101.43.213.235,17.17.17.17,TCP,3096.0,23.0,7.0,DENY,6.0
999998,01/03/2023 10:54,66.249.68.3,17.17.17.17,TCP,41389.0,443.0,1.0,PERMIT,6.0
999999,01/03/2023 10:54,40.77.167.237,17.17.17.17,TCP,55360.0,443.0,1.0,PERMIT,6.0